monolog:
  handlers:
    main:
      type: stream
      path: "%kernel.logs_dir%/%kernel.environment%.log"
      level: debug
      channels: ["!event"]

    doctrine:
      type: stream
      path: "%kernel.logs_dir%/doctrine_%kernel.environment%.log"
      level: debug
      channels: ["doctrine"]