shared:
  resource: '../src/SharedKernel/Infrastructure/Symfony/routes.yaml'

items:
  resource: '../src/Context/Items/Item/Infrastructure/Symfony/routes.yaml'


coins:
  resource: '../src/Context/Coins/Coin/Infrastructure/Symfony/routes.yaml'

customers:
  resource: '../src/Context/Customers/Customer/Infrastructure/Symfony/routes.yaml'